model:
  MCSDNet:
    ckpt: None
    checkpoint_num: 50
    layer_channels: [64,128,256,512]
    encoder:
      name: MultiScaleEncoder
      in_channels: 1
      batch: False
      group_norm: True
      interpolation: False
      residual: False
      num_groups: 4
      aspp: True
    decoder:
      name: ConvDecoder
      out_layer_channels: [64,128,256,512]
      out_channels: 1
      batch: False
      residual: False
      group_norm: True
      num_groups: 4
      interpolation: True
      last_layer: False
      level: False
    bottom: 
      name: STTransformer
      in_channels: 512
      out_channels: 128
      level: 4
      kernel_size: 21
      shortcut: False
      mlp_ratio: 4
      drop: 0.0
      drop_path: 0.1
      attn_shortcut: True
      dynamic: mix
      fuse: attn
      dilation: 3
      reduction: 16
      timesteps: 12
      conv: mix
      spatio_attn: cbam
      temporal_attn: default
      groups: 6
      aggregation: concat
      shape: [12,128,20,32]
      temporal: True
      spatial: True
      mlp_layer: False
      pos_emb: False
    dataset:
      name: cloud
      width: 256
      height: 160
      batch: 4
      series: True
      interval: 15
      frames: 12
      patch: None
      region: None
    trainer:
      decay: 0.0
      loss: FocalLoss
      epochs: 50
      lr: 0.001
      optimizer: Adam
      scheduler: ReduceLROnPlateau
      ratio: 0.1